version: "3.8"

services:
  front-end:
    container_name: frontend
    image: marble-arch-frontend
    build: ./manager_service
    stdin_open: true
    ports:
      - 3000:80
    networks:
      - react-app
    depends_on:
      - backend
  backend:
    image: backend
    build: ./server
    ports:
      - 7500:7500
    networks:
      - react-app
