version: "3"

services:
  front-end:
    container_name: frontend
    image: marble-arch-frontend
    build: ./my-app
    stdin_open: true
    ports:
      - 3000:80
    networks:
      - marble-arch
    depends_on:
      - backend
  backend:
    image: backend
    build: ./server
    ports:
      - 7500:7500
    networks:
      - marble-arch
networks:
  marble-arch: {}
